"""empty message

Revision ID: 388c6fdd072f
Revises: 06c86f4dc502
Create Date: 2024-01-19 22:41:41.076729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388c6fdd072f'
down_revision = '06c86f4dc502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('medicine_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicines', schema=None) as batch_op:
        batch_op.alter_column('medicine_name',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
