"""empty message

Revision ID: 3f4be19e7ae8
Revises: 
Create Date: 2024-01-24 18:59:46.836953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4be19e7ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=250), nullable=False),
    sa.Column('API_id', sa.String(), nullable=True),
    sa.Column('has_psum', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_pharmacy', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pharmacies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_name', sa.String(length=200), nullable=False),
    sa.Column('SOE_pharmacy_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_24h', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('working_hours', sa.String(), nullable=True),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('SOE_pharmacy_number')
    )
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('availability_status', sa.Enum('AVAILABLE', 'NOT_AVAILABLE', name='availabilitystatus'), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('requested_date', sa.DateTime(), nullable=True),
    sa.Column('validity_date', sa.DateTime(), nullable=True),
    sa.Column('order_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COMPLETED', name='orderstatus'), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('pharmacy_id', sa.Integer(), nullable=True),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Association_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'patient_id', 'pharmacy_id', 'medicine_id', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Association_table')
    op.drop_table('orders')
    op.drop_table('availability')
    op.drop_table('pharmacies')
    op.drop_table('patients')
    op.drop_table('users')
    op.drop_table('medicines')
    # ### end Alembic commands ###
